### PR TITLE
Allow FIRRTL to run on Travis

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I wan to add Chisel3 tests to the RocketChip travis so we don't keep getting breakages.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
@azidar @jackkoenig Does anyone look at FIRRTL PRs?

**Comment by jackkoenig** [comment]
Yes we do, do you need this looked at tonight?

@azidar <https://github.com/azidar> @jackkoenig
<https://github.com/jackkoenig> Does anyone look at FIRRTL PRs?

—
Reply to this email directly or view it on GitHub
<https://github.com/ucb-bar/firrtl/pull/83#issuecomment-192821326>.

**Comment by palmer-dabbelt** [comment]
Nope, I just wanted to know if I should merge it myself.

**Comment by jackkoenig** [comment]
Look good to me

**Pull request merged**
