### PR TITLE
Proposal for cleaning up the IR

### PR DESCRIPTION
**Pull request by jackkoenig**
Originally proposed some of these changes in #94 here is a proposed cleanup.

I lengthened the names of most things, but I'm still partial to reasonable abbreviations. The problem is that some things start to get long...See stuff in MemoryPortField area, Orientation, and the fact that I did not extend PrimOp to PrimitiveOperation. I think spelling out Expression (as opposed to Expr) and Statement (as opposed to Stmt) suggests we should spell out PrimOp as well. 

Most of the changes here are minor and not controversial:

1. Flip -> Orientation
1. case class Name() -> case object Name
1. Stmt -> Statement
1. `exp` abbreviation -> `expr`
1. Add GroundType and AggregateType
1. [US]IntValue -> [US]IntLiteral and creation of superclass Literal
1. CamelCase and match spec for PrimOps
  1. That being said, with reduction operations it could be confusing eg. `OrOp` vs `OrrOp`
  1. The above *should* be fixed with ScalaDoc comments
1. AST -> FIRRTLNode

### CODE REVIEW

**Comment by jackkoenig** [comment]
The second commit in this PR address some of the discussion in #148 

I'm not sure that it addresses @aswaterman's concern https://github.com/ucb-bar/firrtl/pull/148#discussion_r61216334, but I think this is in the general direction of more explicit representation of memory ports in the IR.

Note that there are two proposals for Memory Ports as indicated by the comments.

**Comment by jackkoenig** [comment]
The proposed Memory Port changes *could* address Andrew's concern if we changed the way references work. We could change references to contain an actual reference to the node being referred rather than the String name of it. We could also instead provide some sort of Circuit Analysis that provides this feature, and then use that instead of checking string names as in the issue Andrew was pointing out.

**Comment by chick** [comment]
@jackkoenig I don't have any good ideas on the name expansion.  Personally I'd be ok with PrimitiveOperation, but I use an IDE that means I never type stuff like that.  I don't think that any rule you make regarding naming conventions will be without problems, your are living this code right now, just do what you think is right.

**Comment by azidar** [comment]
> The proposed Memory Port changes could address Andrew's concern if we changed the way references work. We could change references to contain an actual reference to the node rather than its String name. We could also instead provide some sort of "Analysis" that provides this actual reference feature.

I'm not sure I understand - you mean WRef would replace its name field with a Stmt field?

**Comment by jackkoenig** [comment]
> >The proposed Memory Port changes could address Andrew's concern if we changed the way references work. We could change references to contain an actual reference to the node rather than its String name. We could also instead provide some sort of "Analysis" that provides this actual reference feature.

> I'm not sure I understand - you mean WRef would replace its name field with a Stmt field?

Perhaps not a Stmt field since WRef could refer to Ports as well, could be an IsDeclaration or something like that.

**Comment by azidar** [comment]
Yeah, I understand it is tempting to put the actual node there instead of a string, but this is very intentional in the design of the IR. Not only do we want the Firrtl graph to be a tree, we really want to prevent having stale data in the graph, and this would be a huge cause of headaches because we would essentially need to update these after every since pass.

**Comment by jackkoenig** [comment]
Oh yeah that makes sense, I was more just referring to how we could better handle the issue Andrew brought up in #148 . I think providing a utility function (or analysis) that creates a mapping from WRef and the like to their declarations would work equally well

**Comment by jackkoenig** [comment]
Replaced by #163

**Pull request closed without merging**
