### PR TITLE
fix duplicate memory detection

### PR DESCRIPTION
**Pull request by donggyukim**
Addresses #333: `uniqueueMems` should be constructed in terms of the entire circuit.

@shunshou I might have changed the algorithm with my refactoring. Also `eqMems` changes in accordance with the recent refactoring.

### CODE REVIEW

**Comment by shunshou** [comment]
Hm ok... I don't remember any more... info was always a field of DefMemory, right? o_O Strange that I didn't exclude it...... Now info is just source locator, so I definitely don't want to look at it for uniquness... And other added annotations definitely still need to match. 

Not sure why the tests get an UnknownType error... code seems reasonable...

**Comment by donggyukim** [comment]
I fix `eqMems` to pass tests

**Comment by colinschmidt** [comment]
Is this branch ready for a trial run on my codebase?

**Comment by donggyukim** [comment]
@colinschmidt Yeah, let me know if this also works for your case.

**Comment by jackkoenig** [comment]
Note that due to a change to chisel3, all Travis tests are currently failing. I'm trying to fix it.

**Comment by colinschmidt** [comment]
Something weird is happening on this branch, I don't actually get any conf file out. I think that this could be due to several recent PRs(rocket-chip is far behind firrtl/master) of  so I'll try to do a bisect and see what I come up with.

**Comment by colinschmidt** [comment]
Ok so #337 was this issue according to bisect. Once thats resolved I'll test this again.

**Comment by colinschmidt** [comment]
with help from @chick I got a fix for #337 and was able to verify that this branch fixes my issue. Thanks!

**Comment by shunshou** [comment]
Looks good to me pending Travis pass? Sorry, should've caught the ref myself.

**Pull request merged**
