### PR TITLE
Move verilog_rename_n() into VerilogRename object …

### PR DESCRIPTION
**Pull request by ucbjrl**
… so it's available outside firrtl (chisel-testers).

### CODE REVIEW

**Comment by aswaterman** [comment]
How is the tester going to depend on this?  If it's using it to attempt to mangle names the same way that FIRRTL does, it's not sufficient, because of name conflicts when flattening aggregates.

**Comment by ucbjrl** [comment]
I believe this is applied after any name mangling. It's replacing existing duplicate code in PeekPokeTesterUtils.validName().

**Comment by azidar** [comment]
Yeah, @aswaterman is correct, @ucbjrl you will also need to run the Uniquify pass as well, I believe. Perhaps this will be done later (as this is a simple first step to get 95% of the way there).

**Comment by ucbjrl** [comment]
Sure, all this is well and good. My point is duplicating existing firrtl code in testers is bad. There is coupling and it's better to acknowledge it than hide it by duplicating code. We do need a better API, but until it's designed, let's at least acknowledge the dependency.

**Comment by jackkoenig** [comment]
Tester is going to use annotations. No longer necessary.

**Pull request closed without merging**
