### PR TITLE
Change RW port names

### PR DESCRIPTION
**Pull request by shunshou**
* Updated FIRRTL spec + related code for readwrite ports.
    (write) data -> wdata & mask -> wmask for clarity

* Also removed simple.fir that snuck into master branch.

### CODE REVIEW

**Comment by azidar** [comment]
data -> wdata and mask -> wmask does make more sense insofar as clarity is concerned. This is a backwards incompatible change, but since Chisel3 has only recently been able to generate read-write ports, perhaps this is ok? any thoughts @aswaterman @jackkoenig

**Comment by aswaterman** [comment]
This is more consistent and IMO is worth the backwards incompatibility at this juncture.  I assume @shunshou is making the corresponding changes to Chisel.

**Comment by shunshou** [comment]
From previous discussions (re: inferReadWrite), I think Chisel is agnostic to explicit readwrite ports. I just changed the InferReadWrite FIRRTL pass to be consistent with the spec change.

**Comment by shunshou** [comment]
@jackkoenig any opinions? It'd be great if a decision could be made either way, as that affects how I'd recode my pass. I assume the sooner the better, as the backwards incompatibility becomes more of a problem the longer people have to use the InferReadWrite pass.

**Comment by jackkoenig** [comment]
I agree with this change and agree that we should make backwards incompatible changes sooner rather than later, I will merge

**Pull request merged**
