### PR TITLE
Transform for blackboxing memories - rebased

### PR DESCRIPTION
**Pull request by jackkoenig**
Replaces #249 

I merged a few commits together and changed messages to leave a blank line after the first line.

### CODE REVIEW

**Comment by shunshou** [comment]
Looks like it's ok? At least +1,137 −44 is the same? 

Re: Jenkins -- I'm not super sure how it works. I assume it just checks that default rocket FIRRTL passes? 

I can separately run assembly tests on this version now that master's been merged (rather than merging master locally).

**Comment by jackkoenig** [comment]
I think Jenkins runs Chisel3, Firrtl, and rocket chips tests (at least for default configurations). I hope we can add other configurations and/or BOOM, etc. in the future.

If you can run the rocket-chip tests and confirm it works I can go ahead and merge (which will actually trigger jenkins anyway because it always runs when master changes)

**Comment by shunshou** [comment]
I'm running with my transform turned on, and at least it's already gotten through the first couple of tests. It'll take some time to get through all of them... Jenkins won't catch when my transform is on, but at least it'll prove that my transform didn't break anything when it's not used...

**Comment by shunshou** [comment]
@ben-k @mwachs5 -- this should be more or less the same as versions you guys have tried in the past, save for lots of code style + restructuring tweaks. Can you guys double check that the versions of Rocket you guys are using compile + simulate? 

I've run with the generic replseqmem branch, but if you have anything fancier to try this on before this initial version gets merged, that'd be a good sanity check.

**Comment by mwachs5** [comment]
I've been keeping up to date with your branch and tried with the latest as of Sunday, but I can try with this exact version in the morning. Can you update the replseqmem rocket -chip branch (or I can if it's simple)

**Comment by shunshou** [comment]
@jackkoenig the assembly tests I ran looked OK. 
@mwachs5 I bumped rocket-chip replseqmem

**Pull request merged**
