### PR TITLE
Fix pad, second try

### PR DESCRIPTION
**Pull request by azidar**
Bugfix: pad is max(width,const) during constprop

### CODE REVIEW

**Comment by jackkoenig** [comment]
This seems to be causing an error in FixedPoint in chisel3

**Comment by jackkoenig** [comment]
Where are we on a possible test to illustrate the bug?

**Comment by azidar** [comment]
The bug was a mismatch with chisel, the version of master that had been pulled in was too dated. Just pulling from master fixed the error. So... I think a test is unnecessary.

**Comment by jackkoenig** [comment]
By bug I don't mean the break with chisel3, I mean the bug this PR is fixing

**Pull request merged**
