### PR TITLE
Fix bits type

### PR DESCRIPTION
**Pull request by jackkoenig**
This commit fixes a host of minor bugs and adds the appropriate tests to find them. These bug fixes are required in order for the compiler to be rerun after lowering (eg. for transformations that want to operate on low FIRRTL then rerun the compiler). 

The one thing I'm not super sure about is whether or not the constant propogation of pad widths I added to Legalize should be there. This is a linting warning so it's not clear that it is a required "legalization" but the warning it was exercising used to be an error in Verilator so it's probably a good idea to not exercise it. 

I also added the concept of "Debug Compilers" which extend the compilers defined in main by inserting check passes in between the passes already run. I think this concept could be extended in various ways to have the testing infrastructure run more checks than the regular compiler does (as we've talked about in the past).

### CODE REVIEW

**Comment by jackkoenig** [comment]
This PR is required for my next PR (adding the substitute memories pass) which should fix #147 and #155

**Comment by azidar** [comment]
I think the Legalization pass should be subsumed by the PadWidths pass and Constant propagation. The legalizeBits/legalizePad should be done during constant propagation, and legalize connect should be done during PadWidths.

The changes to account for SInt's are very good.

The Debug compilers is a good idea, I think there is more to flesh out there, but I'm ok accepting the change for now.

**Comment by aswaterman** [comment]
I'm a little nervous about mandating constant propagation for correct code generation, but OTOH, having a separate legalization pass results in code duplication.  Maybe the former is the pragmatic thing to do.

**Comment by jackkoenig** [comment]
I definitely think there is more to flesh out with the Debug Compilers, for instance it would be great if each pass had a `checkInvariants` function or something just to give us a little more confidence they're doing the right thing.

**Comment by jackkoenig** [comment]
I think we might be able to do both. We could essentially combine the two into a single pass with "optimization" and "required" propagation functions. This pass accepts an argument to select which we're doing as it's constructor. Then the ConstantPropogation and Legalize passes are subclasses of this class, and the compiler chooses which to run based on command line options

**Comment by azidar** [comment]
Another alternative is to add the required prop functions to PadWidths? PadWidths is essentially a legalization pass, in that it also removes Verilator warnings. Then again, some verilator warnings are also removed during constant propagation.....

**Comment by jackkoenig** [comment]
Replaced by #296

**Pull request closed without merging**
