### PR TITLE
Eliminate useless ports

### PR DESCRIPTION
**Pull request by terpstra**
This adds a pass which prunes disconnected input and output ports. These were causing us problems with achieving coverage.

Please pay special attention and review the DeadCodeElimination changes. This PR makes the dead code elimination significantly more aggressive, which may have corner cases I didn't exercise in Rocket.

### CODE REVIEW

**Comment by terpstra** [comment]
@jackkoenig Are you the correct person to point at this pass?

**Comment by terpstra** [comment]
Hmm. I see there are unit tests which don't use their ports, but depend on the result having exactly the specified ports. I could resolve these by inserting a body that makes the ports actually used. Or this port removal pass could be made into a command-line option. What's best?

**Comment by azidar** [comment]
I think aggressive dce and port elimination should be an optional feature. Often, new users of Chisel/Firrtl get extremely confused when they end up with an empty module.

To do this, follow the example of InlineInstances (e.g. extend Transform, not Pass). Ideally, I'd like to see the following annotations:

- Turn on the pass (like InlineInstancesAnnotation)
- Preserve a wire/port/node/etc. <- this allows future transforms, libraries, etc. to run your pass, even if they have an unused port they want to hook up later.

In order for the PR to be accepted, you'll need to write multiple tests in `src/test/scala/firrtlTests`, as well as write some more comments in your transform explaining the major functions.

**Comment by shunshou** [comment]
@azidar idk how long it'll take to approve this PR. 

1) It'd be useful for me since who knows when RawModule will ever be merged into chisel. 
2) Even if I don't get something that eliminates unconnected ports, it'd be useful at least to see which ports are actually unconnected...

**Comment by azidar** [comment]
@terpstra @shunshou I'll go ahead and take care of this PR.

**Comment by azidar** [comment]
Superceded by #549

**Pull request closed without merging**
